# Generated by Django 4.1.4 on 2023-01-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_classroom_table_alter_student_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
