# Generated by Django 4.1.4 on 2023-01-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_classroom_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
