# Generated by Django 4.1.4 on 2023-01-03 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_studentproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('administration.teacher',),
        ),
        migrations.AlterModelOptions(
            name='studentproxy',
            options={'ordering': ['id']},
        ),
    ]
