# Generated by Django 4.1.4 on 2023-01-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_teacherproxy_alter_studentproxy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomProxy',
            fields=[
            ],
            options={
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('administration.classroom',),
        ),
    ]
